ebin/lz4.app

Restore ebin/lz4.app

---

.bazelrc
.github/workflows/test.yml
BUILD.bazel
BUILD.lz4_src
MODULE.bazel
WORKSPACE.bazel
platforms/BUILD.bazel
toolchains/BUILD.bazel

Adopts the latest rules_erlang

Use rules_erlang 3.1.0

---

BUILD.bazel
BUILD.lz4_src
MODULE.bazel
WORKSPACE.bazel
extensions.bzl

This has effects on paths, so this becomes a bzlmod only bazel build

Make fully bzlmod compatible

---

MODULE.bazel

Automated changes created by https://github.com/rabbitmq/lz4-erlang/actions/runs/3234224417 using the [create-pull-request](https://github.com/peter-evans/create-pull-request) GitHub action in the Update OTP Patch Versions workflow.

Adopt otp 24.3.4.6

---

.bazelrc
MODULE.bazel

Use rules_erlang 3.8.1

---

MODULE.bazel

Automated changes created by https://github.com/rabbitmq/lz4-erlang/actions/runs/3239539151 using the [create-pull-request](https://github.com/peter-evans/create-pull-request) GitHub action in the Update OTP Patch Versions workflow.

Adopt otp 25.1.1

---

MODULE.bazel

Automated changes created by https://github.com/rabbitmq/lz4-erlang/actions/runs/3318045106 using the [create-pull-request](https://github.com/peter-evans/create-pull-request) GitHub action in the Update OTP Patch Versions workflow.

Adopt otp 25.1.2

---

MODULE.bazel

Automated changes created by https://github.com/rabbitmq/lz4-erlang/actions/runs/3834822035 using the [create-pull-request](https://github.com/peter-evans/create-pull-request) GitHub action in the Update OTP Patch Versions workflow.

Adopt otp 24.3.4.7

---

MODULE.bazel

Automated changes created by https://github.com/rabbitmq/lz4-erlang/actions/runs/3945322561 using the [create-pull-request](https://github.com/peter-evans/create-pull-request) GitHub action in the Update OTP Patch Versions workflow.

Adopt otp 24.3.4.8

---

MODULE.bazel

Automated changes created by https://github.com/rabbitmq/lz4-erlang/actions/runs/3954956609 using the [create-pull-request](https://github.com/peter-evans/create-pull-request) GitHub action in the Update OTP Patch Versions workflow.

Adopt otp 25.1.2.1

---

MODULE.bazel

Automated changes created by https://github.com/rabbitmq/lz4-erlang/actions/runs/4258963533 using the [create-pull-request](https://github.com/peter-evans/create-pull-request) GitHub action in the Update OTP Patch Versions workflow.

Adopt otp 24.3.4.9

---

MODULE.bazel

Automated changes created by https://github.com/rabbitmq/lz4-erlang/actions/runs/4453344264 using the [create-pull-request](https://github.com/peter-evans/create-pull-request) GitHub action in the Update OTP Patch Versions workflow.

Adopt otp 24.3.4.10

---

MODULE.bazel

Automated changes created by https://github.com/rabbitmq/lz4-erlang/actions/runs/4770581074 using the [create-pull-request](https://github.com/peter-evans/create-pull-request) GitHub action in the Update OTP Patch Versions workflow.

Adopt otp 24.3.4.11

---

MODULE.bazel

Automated changes created by https://github.com/rabbitmq/lz4-erlang/actions/runs/5030080821 using the [create-pull-request](https://github.com/peter-evans/create-pull-request) GitHub action in the Update OTP Patch Versions workflow.

Adopt otp 25.3.2

---

MODULE.bazel

Use the latest rules_erlang

---

MODULE.bazel

Automated changes created by https://github.com/rabbitmq/lz4-erlang/actions/runs/5128429380 using the [create-pull-request](https://github.com/peter-evans/create-pull-request) GitHub action in the Update OTP Patch Versions workflow.

Adopt otp 24.3.4.12

---

MODULE.bazel

Automated changes created by https://github.com/rabbitmq/lz4-erlang/actions/runs/5128429380 using the [create-pull-request](https://github.com/peter-evans/create-pull-request) GitHub action in the Update OTP Patch Versions workflow.

Adopt otp 25.3.2.1

---

extensions.bzl

The previous link no longer works

Update the link for the pdf file used for testing

---

WORKSPACE.bazel

Remove unneeded portions of WORKSPACE.bazel

---

MODULE.bazel

Automated changes created by https://github.com/rabbitmq/lz4-erlang/actions/runs/5227796914 using the [create-pull-request](https://github.com/peter-evans/create-pull-request) GitHub action in the Update OTP Patch Versions workflow.

Adopt otp 26.0.1

---

MODULE.bazel

Automated changes created by https://github.com/rabbitmq/lz4-erlang/actions/runs/5233286507 using the [create-pull-request](https://github.com/peter-evans/create-pull-request) GitHub action in the Update OTP Patch Versions workflow.

Adopt otp 25.3.2.2

---

MODULE.bazel

Automated changes created by https://github.com/rabbitmq/lz4-erlang/actions/runs/5418880486 using the [create-pull-request](https://github.com/peter-evans/create-pull-request) GitHub action in the Update OTP Patch Versions workflow.

Adopt otp 26.0.2

---

MODULE.bazel

Automated changes created by https://github.com/rabbitmq/lz4-erlang/actions/runs/5428837434 using the [create-pull-request](https://github.com/peter-evans/create-pull-request) GitHub action in the Update OTP Patch Versions workflow.

Adopt otp 24.3.4.13

---

MODULE.bazel

Automated changes created by https://github.com/rabbitmq/lz4-erlang/actions/runs/5428837434 using the [create-pull-request](https://github.com/peter-evans/create-pull-request) GitHub action in the Update OTP Patch Versions workflow.

Adopt otp 25.3.2.3

---

.bazelrc
.github/workflows/test.yml
BUILD.bazel
MODULE.bazel
extensions.bzl
toolchains/BUILD.bazel
toolchains/cc_toolchain_config.bzl

Add additional rules for cross compiling with aarch64-linux-gnu-gcc

---

MODULE.bazel

Automated changes created by https://github.com/rabbitmq/lz4-erlang/actions/runs/5582895846 using the [create-pull-request](https://github.com/peter-evans/create-pull-request) GitHub action in the Update OTP Patch Versions workflow.

Adopt otp 25.3.2.4

---

MODULE.bazel

Automated changes created by https://github.com/rabbitmq/lz4-erlang/actions/runs/5722088940 using the [create-pull-request](https://github.com/peter-evans/create-pull-request) GitHub action in the Update OTP Patch Versions workflow.

Adopt otp 25.3.2.5

---

.github/workflows/publish-rabbitmq-bcr.yml
.github/workflows/release.yml

publishes to our bzlmod registry rabbitmq/bazel-central-registry@erlang-packages

Add release automation

---

MODULE.bazel

Automated changes created by https://github.com/rabbitmq/lz4-erlang/actions/runs/6117184228 using the [create-pull-request](https://github.com/peter-evans/create-pull-request) GitHub action in the Update OTP Patch Versions workflow.

Adopt otp 25.3.2.6

---

ebin/lz4.app
erlang.mk

Upgrade erlang.mk

---

MODULE.bazel

Automated changes created by https://github.com/rabbitmq/lz4-erlang/actions/runs/8601803355 using the [create-pull-request](https://github.com/peter-evans/create-pull-request) GitHub action in the Update OTP Patch Versions workflow.

Adopt otp 25.3.2.10

---

MODULE.bazel

Automated changes created by https://github.com/rabbitmq/lz4-erlang/actions/runs/8601803355 using the [create-pull-request](https://github.com/peter-evans/create-pull-request) GitHub action in the Update OTP Patch Versions workflow.

Adopt otp 24.3.4.16

---

MODULE.bazel

Automated changes created by https://github.com/rabbitmq/lz4-erlang/actions/runs/8670598361 using the [create-pull-request](https://github.com/peter-evans/create-pull-request) GitHub action in the Update OTP Patch Versions workflow.

Adopt otp 25.3.2.11

---

MODULE.bazel

#93 introduced a load statement for it

Declare the dependency on rules_cc

---

MODULE.bazel

Automated changes created by https://github.com/rabbitmq/lz4-erlang/actions/runs/8933519815 using the [create-pull-request](https://github.com/peter-evans/create-pull-request) GitHub action in the Update OTP Patch Versions workflow.

Adopt otp 25.3.2.12
